include $(SRC_RT)/myOS/kernel/mem/Makefile

KERNEL_OBJS = output/myOS/kernel/tick.o \
	      output/myOS/kernel/wallClock.o \
		  output/myOS/kernel/task.o \
		  output/myOS/kernel/taskPara.o \
		  output/myOS/kernel/taskQueue.o \
		  output/myOS/kernel/taskArrv.o \
		  output/myOS/kernel/schedulers.o \
		  output/myOS/kernel/scheduler.o \
		  output/myOS/kernel/scheduleTest.o \
	      $(MEM_OBJS)
